flags: {}
user-message: ! 'Warning (added by new or init): Specified resolver could not satisfy
  all dependencies. Some external packages have been added as dependencies.

  You can suppress this message by removing it from stack.yaml

'
extra-package-dbs: []
packages:
- '.'
extra-deps:
- network-socket-options-0.2.0.1
- utf8-string-1.0.1.1
resolver: ghc-8.0.2
